### ISSUE TITLE
Old links to SeqNN in basenji_sat.py and basenji_sed.py

### ISSUE THREAD

**Issue by ikaka89** [calico/basenji#24]
Both basenji_sat.py and basenji_sed.py called a attributes that don't exist in SeqNN class

{'batch_size': 4, 'cnn_dilation': [1, 1, 1, 1, 1, 2, 4, 8, 16, 32, 64, 1], 'link': 'softplus', 'batch_buffer': 4096, 'learning_rate': 0.002, 'cnn_filters': [128, 128, 192, 256, 256, 32, 32, 32, 32, 32, 32, 384], 'cnn_dropout': 0.1, 'adam_beta2': 0.98, 'cnn_dense': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0], 'loss': 'poisson', 'cnn_filter_sizes': [20, 7, 7, 7, 3, 3, 3, 3, 3, 3, 3, 1], 'cnn_pool': [2, 4, 4, 4, 1, 0, 0, 0, 0, 0, 0, 0], 'num_targets': 3, 'adam_beta1': 0.97, 'optimizer': 'adam', 'target_pool': 128}
Targets pooled by 128 to length 1024
Convolution w/ 3 384x1 filters to final targets
Targets pooled by 128 to length 1024
Convolution w/ 3 384x1 filters to final targets
2018-09-24 19:52:17.490718: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Mutating sequence 1 / 1
Traceback (most recent call last):
  File "/shared/workspace/software/basenji/bin/basenji_sat.py", line 660, in <module>
    main()
  File "/shared/workspace/software/basenji/bin/basenji_sat.py", line 189, in main
    sat_preds = model.predict(sess, batcher_sat,
AttributeError: 'SeqNN' object has no attribute 'predict'

The predict attribute seems to exist in SeqNNOrig.

**Comment by davek44** [comment]
Sorry about that. I'm transitioning everything to work with the more effective tf.data API and replacing those scripts with new versions. I fixed basenji_sat.py and pushed the new version. What's the error for basenji_sed.py? predict_genes is intact.

**Comment by davek44** [comment]
I tested and found a couple problems with basenji_sed.py that I also fixed. Works now for me, so pull the latest and give it a shot.

**Comment by ikaka89** [comment]
Hi Dave,

I still get the following error with basenji_sat.py:-

{'optimizer': 'adam', 'cnn_filter_sizes': [20, 7, 7, 7, 3, 3, 3, 3, 3, 3, 3, 1], 'link': 'softplus', 'cnn_dense': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0], 'cnn_filters': [128, 128, 192, 256, 256, 32, 32, 32, 32, 32, 32, 384], 'learning_rate': 0.002, 'loss': 'poisson', 'batch_size': 4, 'target_pool': 128, 'adam_beta2': 0.98, 'adam_beta1': 0.97, 'batch_buffer': 4096, 'num_targets': 3, 'cnn_dilation': [1, 1, 1, 1, 1, 2, 4, 8, 16, 32, 64, 1], 'cnn_dropout': 0.1, 'cnn_pool': [2, 4, 4, 4, 1, 0, 0, 0, 0, 0, 0, 0]}
Targets pooled by 128 to length 1024
Convolution w/ 3 384x1 filters to final targets
Targets pooled by 128 to length 1024
Convolution w/ 3 384x1 filters to final targets
2018-10-01 12:47:08.147278: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Mutating sequence 1 / 1
Traceback (most recent call last):
  File "/shared/workspace/software/basenji/bin/basenji_sat.py", line 660, in <module>
    main()
  File "/shared/workspace/software/basenji/bin/basenji_sat.py", line 190, in main
    rc=options.rc, shifts=options.shifts)
TypeError: predict_h5() got an unexpected keyword argument 'rc'

**Comment by davek44** [comment]
I pushed a fix for that one, too. Thanks

**Comment by ikaka89** [comment]
Thanks so much. Works for me too.
